name: CI/CD with Docker on DigitalOcean Registry

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: registry.digitalocean.com/imgreg-m101/webfe-simple:latest
  CONTAINER_NAME: webfe-simple
  PORT: 4000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Sesuaikan dengan versi Node.js

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Run tests (opsional)
    - name: Run tests
      run: npm test

    # 5. Build Docker image
    - name: Build Docker image
      run: |
        docker build -t $DOCKER_IMAGE .

    # 6. Log in to DigitalOcean Container Registry
    - name: Docker login to DigitalOcean Registry
      run: |
        echo "${{ secrets.REGISTRYDO_TOKEN }}" | docker login registry.digitalocean.com -u "${{ secrets.REGISTRYDO_USERNAME }}" --password-stdin

    # 7. Push Docker image to DigitalOcean Registry
    - name: Push Docker image
      run: docker push $DOCKER_IMAGE
    
    # 8. Deploy application via SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODSM101_HOST }}
        username: ${{ secrets.PRODSM101_USERNAME }}
        key: ${{ secrets.PRODSM101_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull $DOCKER_IMAGE
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker run -d --name $CONTAINER_NAME -p $PORT:$PORT --restart always $DOCKER_IMAGE
